name: 'Deploy workflow'

on: [push]

jobs:
  
  Build-IOS:
    name: 'Build-IOS'
    runs-on: macos-latest

    env:
      QT_VERSION: 6.4.1
      QIF_VERSION: 4.4

    steps:
    - name: 'Setup xcode'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4'

    - name: 'Install desktop Qt'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'qtremoteobjects qt5compat qtshadertools'
        dir: ${{ runner.temp }}
        set-env: 'true'

    - name: 'Install ios Qt'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'mac'
        target: 'ios'
        modules: 'qtremoteobjects qt5compat qtshadertools'
        dir: ${{ runner.temp }}
        setup-python: 'true'
        set-env: 'true'
        extra: '--external 7z'

    - name: 'Install go'
      uses: actions/setup-go@v3

    - name: 'Setup gomobile'
      run: |
          export PATH=$PATH:~/go/bin
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

    - name: 'Get sources'
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 10

    - name: 'Setup ccache'
      uses: hendrikmuhs/ccache-action@v1.2

    - name: 'Build project'
      run: |
        export QT_BIN_DIR="${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/ios/bin"
        export QT_MACOS_ROOT_DIR="${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/macos"
        export QT_IOS_BIN=$QT_BIN_DIR
        export PATH=$PATH:~/go/bin
        mkdir build-ios
        $QT_IOS_BIN/qt-cmake . -B build-ios -GXcode -DQT_HOST_PATH=$QT_MACOS_ROOT_DIR

    - name: iOS Build/Release With Multiple Targets Action
      uses: sparkfabrik/ios-build-action@v2.0.0
      with:
        upload-to-testflight: true
        increment-build-number: true
        configuration: Release
        export-method: app-store
        project-path: /build-ios/AmneziaVPN.xcodeproj
        scheme: AmneziaVPN
        output-path: build-${{ github.sha }}.ipa
        apple-key-id: ${{ secrets.APPLE_KEY_ID }}
        apple-key-issuer-id: ${{ secrets.APPLE_KEY_ISSUER_ID }}
        apple-key-content: ${{ secrets.APPLE_KEY_CONTENT }}
        team-id: ${{ secrets.TEAM_ID }}
        team-name: ${{ secrets.TEAM_NAME }}
        match-password: ${{ secrets.MATCH_PASSWORD }}
        match-git-url: ${{ secrets.MATCH_GIT_URL }}
        match-git-basic-authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        match-build-type: 'appstore'
